services:
  bot:
    build:
      context: ./
      dockerfile: bot/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - bot-logs:/logs
    networks:
      - botnet
  
  redis:
    image: redis:latest
    ports:
      - "6666:6379"
    volumes:
      - redis-data:/data
    networks:
      - botnet

networks:
  botnet:

volumes:
  redis-data:
  bot-logs: